[tools]
dprint = "0.50.1"
"rust" = "1.89.0"
"cargo:cross" = "0.2.5"

# Tasks

[tasks.build]
description = "Build the project"
run = "cargo build"

[tasks.fix-style]
description = "Auto-format files to address style/lint issues"
run = "dprint fmt"

[tasks.test-style]
description = "Check whether files adhere to style/lint rules"
run = "dprint check"

[tasks.test-unit]
description = "Run unit tests"
run = "cargo test --lib --bins"

[tasks.test-integration]
description = "Run integration tests"
run = "cargo test --test integration_test"

[tasks.test-all]
description = "Run unit, integration, and doc tests"
run = "cargo test"

[tasks.test]
description = "Run all tests (including style, unit, integration, and doc tests)"
depends = ["test-style", "test-all"]

[tasks.build-target]
description = "Build for a specific target (usage: mise run build-target -- <target>)"
run = "scripts/build-target.sh"

[tasks.build-release]
description = "Build cross-platform release binaries for all targets"
run = "scripts/build-release.sh"
