name: "Setup Environment"
description: "Common setup steps: cache Rust directories, setup mise, and install Rust"

runs:
  using: "composite"
  steps:
    - name: Cache Rust directories
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/binstall
          ~/.cargo/env
          ~/.rustup
        key: rust-cache-${{ runner.os }}-${{ hashFiles('.mise.toml') }}
        restore-keys: |
          rust-cache-${{ runner.os }}-

    - name: Setup mise
      uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

    - name: Install and verify Rust toolchain
      shell: bash
      run: |
        # Ensure Rust toolchain is properly installed before running tests
        mise install rust
        # Install required components explicitly
        mise exec rust -- rustup component add rustfmt clippy
        # Verify installation
        mise exec rust -- rustc --version
        mise exec rust -- rustfmt --version
