name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run tests
        run: mise run test

      - name: Verify PR title follows Conventional Commits
        run: |
          # Extract PR title and check if it follows Conventional Commits format
          PR_TITLE="${{ github.event.pull_request.title }}"
          # Regex pattern for Conventional Commits:
          # - Required type: feat|fix|docs|style|refactor|test|chore
          # - Optional scope: (anything except !)
          # - Optional breaking change indicator: !
          # - Required colon and space: ": "
          # - Required description: at least one character
          # Supports: type: desc, type!: desc, type(scope): desc, type(scope)!: desc, type!(scope): desc
          if ! echo "$PR_TITLE" | grep -qE '^(feat|fix|docs|style|refactor|test|chore)(!(\([^)!]+\))?|(\([^)!]+\))!?)?: .+'; then
            echo "❌ Error: PR title must follow Conventional Commits format"
            echo ""
            echo "Expected format: type[!][(scope)]: description"
            echo ""
            echo "Supported types:"
            echo "  • feat     - new feature"
            echo "  • fix      - bug fix"
            echo "  • docs     - documentation changes"
            echo "  • style    - code style changes (formatting, etc.)"
            echo "  • refactor - code refactoring"
            echo "  • test     - adding or modifying tests"
            echo "  • chore    - maintenance tasks"
            echo ""
            echo "Examples:"
            echo "  ✅ feat: add user authentication"
            echo "  ✅ fix(api): resolve timeout issue"
            echo "  ✅ feat!: breaking change to API"
            echo "  ✅ docs(readme): update installation instructions"
            echo ""
            echo "Current title: '$PR_TITLE'"
            exit 1
          fi
          echo "✅ PR title follows Conventional Commits format: $PR_TITLE"

  release-plz-pr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Create release PR with release-plz
        uses: MarcoIeni/release-plz-action@e1b96e8cfeff90d86d37c0e8ba23bf0d84f56ed9 # v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-plz-release:
    # Only run when a release PR is merged to main
    # release-plz creates releases with specific commit message patterns
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Create GitHub release with release-plz
        run: |
          echo "TODO: Implement actual release-plz release creation"
          echo "This step will:"
          echo "1. Create actual GitHub release with tag using release-plz"
          echo "2. Use generated changelog in release description"
          echo "3. Command would be: release-plz release"

  # Build and upload cross-platform binaries when a release is created
  build-and-upload-binaries:
    # TODO: Enable when ready to test actual releases
    # Only run when a tag is created (after release-plz creates the release)  
    if: false # startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build release binaries
        run: |
          # Build for multiple targets using cross
          targets=(
            "x86_64-unknown-linux-gnu"
            "x86_64-pc-windows-msvc"
            "x86_64-apple-darwin"
            "aarch64-apple-darwin"
          )

          for target in "${targets[@]}"; do
            echo "Building for $target..."
            cross build --release --target "$target"

            # Create properly named binaries
            binary_name="mcp-serve"
            case "$target" in
              *windows*)
                binary_name="${binary_name}.exe"
                ;;
            esac

            # Copy to release directory with platform-specific naming
            mkdir -p "release"
            platform_name=$(echo "$target" | sed 's/unknown-//' | sed 's/pc-//')
            cp "target/$target/release/$binary_name" "release/mcp-serve-$platform_name"
          done

          # List built binaries
          echo "Built binaries:"
          ls -la release/

      - name: Upload binaries to release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          files: release/mcp-serve-*
