name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run tests
        run: mise run test

      - name: Verify PR title follows Conventional Commits
        run: |
          # Extract PR title and check if it follows Conventional Commits format
          PR_TITLE="${{ github.event.pull_request.title }}"
          # Regex pattern for Conventional Commits:
          # - Required type: feat|fix|docs|style|refactor|test|chore
          # - Optional scope: (anything except !)
          # - Optional breaking change indicator: !
          # - Required colon and space: ": "
          # - Required description: at least one character
          # Supports: type: desc, type!: desc, type(scope): desc, type(scope)!: desc, type!(scope): desc
          if ! echo "$PR_TITLE" | grep -qE '^(feat|fix|docs|style|refactor|test|chore)(!(\([^)!]+\))?|(\([^)!]+\))!?)?: .+'; then
            echo "❌ Error: PR title must follow Conventional Commits format"
            echo ""
            echo "Expected format: type[!][(scope)]: description"
            echo ""
            echo "Supported types:"
            echo "  • feat     - new feature"
            echo "  • fix      - bug fix"
            echo "  • docs     - documentation changes"
            echo "  • style    - code style changes (formatting, etc.)"
            echo "  • refactor - code refactoring"
            echo "  • test     - adding or modifying tests"
            echo "  • chore    - maintenance tasks"
            echo ""
            echo "Examples:"
            echo "  ✅ feat: add user authentication"
            echo "  ✅ fix(api): resolve timeout issue"
            echo "  ✅ feat!: breaking change to API"
            echo "  ✅ docs(readme): update installation instructions"
            echo ""
            echo "Current title: '$PR_TITLE'"
            exit 1
          fi
          echo "✅ PR title follows Conventional Commits format: $PR_TITLE"

  create-release-pr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Create release PR
        uses: release-plz/action@574c1d0ed8491b294f596b7148bafd08cca6a600 # v0.5.115
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build-binaries:
    # TEMPORARILY DISABLED: Run on all pushes for testing
    # TODO: Restore original condition before merging
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build for ${{ matrix.target }}
        uses: houseabsolute/actions-rust-cross@9a1618ffb70e8374ab5f48fcccea3ebeacf57971 # v1.0.5
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--release"
          strip: true

      - name: Prepare binary for upload
        run: |
          # Create platform-specific directory name
          platform_dir=$(echo "${{ matrix.target }}" | sed 's/unknown-//' | sed 's/pc-//' | sed 's/apple-darwin/macos/' | sed 's/linux-gnu/linux/')

          # Create release directory structure
          mkdir -p "release/$platform_dir"

          # Determine binary name
          binary_name="mcp-serve"
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            binary_name="mcp-serve.exe"
          fi

          # Copy binary to release directory
          cp "target/${{ matrix.target }}/release/$binary_name" "release/$platform_dir/"
          echo "✓ Prepared: $platform_dir/$binary_name"

      - name: Upload binary artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: binary-${{ matrix.target }}
          path: release/
          retention-days: 1

  publish-release:
    # TEMPORARILY DISABLED: Run on all pushes for testing
    # TODO: Restore original condition before merging:
    # Only run when a release PR is merged to main (chore(release): commit messages)
    # if: >
    #   github.event_name == 'push' &&
    #   github.ref == 'refs/heads/main' &&
    #   startsWith(github.event.head_commit.message, 'chore(release):')
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Download all binary artifacts
        uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 # v4.1.1
        with:
          pattern: binary-*
          path: artifacts
          merge-multiple: true

      - name: Organize binaries
        run: |
          # Move all binaries to release directory
          mkdir -p release
          find artifacts -type f -name "mcp-serve*" -exec cp {} release/ \; 2>/dev/null || true

          # If that didn't work, copy the directory structure
          if [ -z "$(ls -A release/ 2>/dev/null)" ]; then
            cp -r artifacts/* release/ 2>/dev/null || true
          fi

          echo "Final release directory structure:"
          find release -type f

      - name: Create GitHub release
        uses: release-plz/action@574c1d0ed8491b294f596b7148bafd08cca6a600 # v0.5.115
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Upload binaries to release
        run: |
          # Verify we have platform directories to upload
          if [ ! -d "release" ] || [ -z "$(ls -A release/)" ]; then
            echo "❌ No platform directories found in release/ directory"
            exit 1
          fi

          # Get the latest release tag (created by release-plz)
          RELEASE_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' 2>/dev/null)
          if [ -z "$RELEASE_TAG" ] || [ "$RELEASE_TAG" = "null" ]; then
            echo "❌ No release found. Release creation may have failed."
            exit 1
          fi

          echo "Found release tag: $RELEASE_TAG"
          echo "Uploading binaries to release..."

          # Track upload status
          upload_count=0
          failed_uploads=()

          # Create archives for each platform and upload them
          cd release
          for platform_dir in */; do
            if [[ -d "$platform_dir" ]]; then
              platform_name=$(basename "$platform_dir")
              archive_name="mcp-serve-$platform_name.tar.gz"

              echo "Creating archive for $platform_name..."
              tar -czf "../$archive_name" -C "$platform_dir" .

              echo "Uploading $archive_name..."
              cd ..
              if gh release upload "$RELEASE_TAG" "$archive_name" --clobber 2>/dev/null; then
                echo "✅ Successfully uploaded $archive_name"
                upload_count=$((upload_count + 1))
              else
                echo "❌ Failed to upload $archive_name"
                failed_uploads+=("$archive_name")
              fi
              cd release
            fi
          done
          cd ..

          # Report results
          echo ""
          echo "Upload summary:"
          echo "  Successfully uploaded: $upload_count binaries"

          if [ ${#failed_uploads[@]} -gt 0 ]; then
            echo "  Failed uploads: ${#failed_uploads[@]}"
            printf '    - %s\n' "${failed_uploads[@]}"
            echo "❌ Some binary uploads failed"
            exit 1
          else
            echo "✅ All $upload_count binaries uploaded successfully to release $RELEASE_TAG"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
